# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'FMSecureTextFieldExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FMSecureTextFieldExample

  pod 'FMSecureTextField', :path => "../FMSecureTextField/"

end
